/*
 * main.c -- euicc: build and check eUICC profile packages.
 *
 * Three commands, and each one is a step a profile author repeats:
 *
 *   euicc build   value notation in, DER out
 *   euicc show    DER in, value notation out
 *   euicc check   either in, a verdict out
 *   euicc diff    what separates a source file from a package
 *
 * check is the one that needed a program rather than a pipeline. A profile
 * package fails in two ways, and until now two tools reported them. The schema
 * states what a value may hold, and the specification states in prose what a
 * package must look like. A profile that satisfies one can violate the other.
 */

#include "euicc.h"

#include <ProfileElement.h>
#include <vn_encoder.h>
#include <libxml/xmlIO.h>
#include <libxslt/xslt.h>

/*
 * Identifiers that asn1c parses and does not keep: INTEGER named numbers and
 * BIT STRING named bits. vn-annotate recovers them and the build links the
 * result; the library carries a weak empty table so a program without one
 * still links. Handing it to the reader and the writer is what makes
 * `algorithmID milenage` readable and what makes show print the name the
 * specification prints rather than the number behind it.
 */
extern const vn_annotations_t vn_generated_annotations;

/*
 * build/gitsha.h is generated by the Makefile on every build (see its
 * comment there for why the SHA moved out of a plain -D): it defines
 * EUICC_GITSHA to HEAD's short hash so a bug report can name the commit
 * that produced the binary. __has_include keeps a build outside of make's
 * orchestration -- no build/ directory, nothing generated -- compiling
 * instead of failing at this line; the fallback below then applies.
 */
#ifdef __has_include
#if __has_include("gitsha.h")
#include "gitsha.h"
#endif
#endif

#ifndef EUICC_VERSION
#define EUICC_VERSION "0.0"
#endif
#ifndef EUICC_GITSHA
#define EUICC_GITSHA "unknown"
#endif
#ifndef EUICC_RULES_DIR
#define EUICC_RULES_DIR "vendor/saip-validator/rules"
#endif
#ifndef EUICC_SKEL_DIR
#define EUICC_SKEL_DIR ""
#endif

#define MAX_PE 4096

/* The reader fails at one place at a time, and both the text report and the
   JSON report want the same detail. */
static char g_parse_error[512];
static int g_parse_element;

/*
 * read_package records where the reader stopped instead of printing it,
 * because check turns it into a finding and diff names the file it came from.
 * Every other command has to say it out loud. Without this a rejected build
 * exits 1 in silence, and silence reads as a tool that is broken rather than
 * as a file that is wrong.
 */
static void
report_parse_error(void) {
    fprintf(stderr, "euicc: cannot read profile element %d: %s\n",
            g_parse_element,
            g_parse_error[0] ? g_parse_error : "not value notation");
}

/* ---- input --------------------------------------------------------------- */

static unsigned char *
slurp(const char *path, size_t *len) {
    FILE *f = path ? fopen(path, "rb") : stdin;
    if(!f) {
        fprintf(stderr, "euicc: cannot open %s\n", path);
        return NULL;
    }
    size_t cap = 1 << 16, n = 0;
    unsigned char *buf = malloc(cap);
    for(;;) {
        if(n == cap) buf = realloc(buf, cap *= 2);
        size_t got = fread(buf + n, 1, cap - n, f);
        if(got == 0) break;
        n += got;
    }
    if(path) fclose(f);
    *len = n;
    return buf;
}

/*
 * Value notation is text and DER is not. A file that starts with a printable
 * character, a brace or a letter is text; DER starts with a tag byte. This is
 * a guess, and -i settles it when the guess is wrong.
 */
static int
looks_like_text(const unsigned char *b, size_t n) {
    for(size_t i = 0; i < n && i < 64; i++) {
        if(b[i] == '\n' || b[i] == '\r' || b[i] == '\t') continue;
        if(b[i] < 0x20 || b[i] > 0x7e) return 0;
    }
    return n > 0;
}

/* The 1-based line that an offset falls on. */
static int
line_at(const unsigned char *buf, size_t off) {
    int line = 1;
    for(size_t i = 0; i < off; i++)
        if(buf[i] == '\n') line++;
    return line;
}

/* The 1-based column, counted from the last newline before the offset -- in
   bytes, deliberately. A terminal indexes bytes and so does this tool
   everywhere; LSP indexes UTF-16 code units, and the server converts at its
   edge, the direction terraform-ls converts in too. */
static int
column_at(const unsigned char *buf, size_t off) {
    size_t start = off;
    while(start > 0 && buf[start - 1] != '\n') start--;
    return (int)(off - start) + 1;
}

/*
 * The reader is handed one value at a time, so it counts from the start of
 * that value and says "line 1" for the first line of the third element in a
 * file. Its position is right and its origin is not the file's, which is what
 * an editor needs. Rewritten here rather than in one command, so that build,
 * show, check and diff all say the same thing.
 *
 * A position on the value's first line also has to move sideways, because the
 * value begins after `valueN ProfileElement ::= ` and not in column one.
 */
static void
absolute_position(char *msg, size_t msgsz, const unsigned char *buf, size_t off) {
    int line = 0, column = 0, consumed = 0;

    if(sscanf(msg, "line %d column %d: %n", &line, &column, &consumed) != 2
       || consumed <= 0)
        return;

    int base_line = line_at(buf, off);
    int abs_line = base_line + line - 1;
    int abs_column = (line == 1) ? column_at(buf, off) + column - 1 : column;

    char rest[512];
    snprintf(rest, sizeof rest, "%s", msg + consumed);
    snprintf(msg, msgsz, "line %d column %d: %s", abs_line, abs_column, rest);
}

/*
 * Every ProfileElement in the input, decoded. Returns the count, or -1.
 *
 * The line each value starts on is recorded as well. A constraint failure and
 * a rule failure both name an element and not a position, and an editor needs
 * a position to mark. The line of the element is the closest true answer.
 */
static int
read_package(const unsigned char *buf, size_t len, int as_text,
             ProfileElement_t **out, int *lines, size_t max) {
    size_t off = 0;
    int n = 0;

    while(off < len) {
        /* Trailing whitespace after the last value is not another value. */
        if(as_text) {
            while(off < len && (buf[off] == '\n' || buf[off] == '\r'
                                || buf[off] == ' ' || buf[off] == '\t')) off++;
            if(off >= len) break;
        }
        /* A file of values carries `valueN <Type> ::= ` before each one. That
           is module syntax, and the library steps over it. */
        if(as_text) off = vn_skip_assignment((const char *)buf, len, off);

        if(n == (int)max) {
            fprintf(stderr, "euicc: more than %zu profile elements\n", max);
            return -1;
        }
        if(lines) lines[n] = as_text ? line_at(buf, off) : 1;
        out[n] = NULL;
        asn_dec_rval_t rv;
        if(as_text) {
            char reason[512] = {0};
            vn_read_options_t ro = {0};
            ro.flags = VN_RF_EOF;
            ro.errbuf = reason;
            ro.errlen = sizeof reason;
            ro.annotations = &vn_generated_annotations;
            rv = vn_decode(0, &asn_DEF_ProfileElement, (void **)&out[n], &ro,
                           buf + off, len - off);
            if(rv.code != RC_OK) {
                snprintf(g_parse_error, sizeof g_parse_error, "%s",
                         reason[0] ? reason : "not value notation");
                absolute_position(g_parse_error, sizeof g_parse_error, buf, off);
                g_parse_element = n + 1;
                return -1;
            }
        } else {
            rv = ber_decode(0, &asn_DEF_ProfileElement, (void **)&out[n],
                            buf + off, len - off);
            if(rv.code != RC_OK) {
                fprintf(stderr, "euicc: cannot decode profile element %d\n", n + 1);
                return -1;
            }
        }
        off += rv.consumed;
        n++;
        if(rv.consumed == 0) break;
    }
    return n;
}

/* ---- output -------------------------------------------------------------- */

static int
write_bytes(const void *b, size_t n, void *key) {
    return fwrite(b, 1, n, (FILE *)key) == n ? 0 : -1;
}

/*
 * The rule set reads one <ProfilePackage> that holds every <ProfileElement>.
 * asn1c writes one element at a time, so the wrapper is added here. The Python
 * validator has a shell script that does the same, and both exist because the
 * schema has no type for a whole package.
 */
static xmlDocPtr
package_to_xml(ProfileElement_t **pe, int n) {
    char *xer = NULL;
    size_t xer_len = 0;
    FILE *mem = open_memstream(&xer, &xer_len);
    if(!mem) return NULL;

    /* asn1c names the outer element after the type, so each value already
       arrives as <ProfileElement>…</ProfileElement>. Adding another wrapper
       here nested them twice, and every rule that looks for
       /ProfilePackage/ProfileElement/header then found nothing. */
    fputs("<ProfilePackage>", mem);
    for(int i = 0; i < n; i++) {
        asn_enc_rval_t er = xer_encode(&asn_DEF_ProfileElement, pe[i],
                                       XER_F_BASIC, write_bytes, mem);
        if(er.encoded == -1) {
            fclose(mem);
            free(xer);
            return NULL;
        }
    }
    fputs("</ProfilePackage>", mem);
    fclose(mem);

    xmlDocPtr doc = xmlReadMemory(xer, (int)xer_len, "package.xml", NULL,
                                  XML_PARSE_NONET | XML_PARSE_NOBLANKS);
    free(xer);
    return doc;
}

/* ---- machine-readable report --------------------------------------------- */

static void
json_str(const char *v) {
    putchar('"');
    for(const char *c = v ? v : ""; *c; c++) {
        if(*c == '"' || *c == '\\') printf("\\%c", *c);
        else if((unsigned char)*c < 0x20) printf("\\u%04x", *c);
        else putchar(*c);
    }
    putchar('"');
}

/*
 * An SVRL location is an XPath, and the part this needs is which profile
 * element it points at: /ProfilePackage/ProfileElement[2]/... yields 2. A
 * location without an index belongs to the package and gets element 0.
 */
static int
element_of(const char *location) {
    const char *m = location ? strstr(location, "ProfileElement[") : NULL;
    return m ? atoi(m + strlen("ProfileElement[")) : 0;
}

static void
json_finding(int first, const char *severity, const char *code,
             const char *text, int line, int column, const char *source) {
    printf("%s\n  {", first ? "" : ",");
    printf("\"severity\": "); json_str(severity);
    printf(", \"code\": ");   json_str(code);
    printf(", \"message\": "); json_str(text);
    printf(", \"line\": %d, \"column\": %d", line, column);
    if(source) { printf(", \"source\": "); json_str(source); }
    putchar('}');
}

/* ---- commands ------------------------------------------------------------ */

static int
cmd_build(const char *in, const char *out, int as_text) {
    size_t len = 0;
    unsigned char *buf = slurp(in, &len);
    if(!buf) return 1;
    if(as_text < 0) as_text = looks_like_text(buf, len);

    ProfileElement_t *pe[MAX_PE];
    int lines[MAX_PE];
    int n = read_package(buf, len, as_text, pe, lines, MAX_PE);
    free(buf);
    if(n < 0) { report_parse_error(); return 1; }

    /* A value that breaks a SIZE or a range is caught before anything is
       written, so a rejected build leaves no half-correct file behind. */
    for(int i = 0; i < n; i++) {
        char reason[512];
        size_t rlen = sizeof reason;
        if(vn_check_constraints(&asn_DEF_ProfileElement, pe[i], reason, &rlen) != 0) {
            fprintf(stderr, "euicc: profile element %d violates the schema: %s\n",
                    i + 1, reason);
            return 1;
        }
    }

    FILE *f = out ? fopen(out, "wb") : stdout;
    if(!f) {
        fprintf(stderr, "euicc: cannot write %s\n", out);
        return 1;
    }
    for(int i = 0; i < n; i++) {
        asn_enc_rval_t er = der_encode(&asn_DEF_ProfileElement, pe[i],
                                       write_bytes, f);
        if(er.encoded == -1) {
            fprintf(stderr, "euicc: cannot encode profile element %d\n", i + 1);
            return 1;
        }
    }
    if(out) fclose(f);
    fprintf(stderr, "euicc: %d profile element%s written\n", n, n == 1 ? "" : "s");
    return 0;
}

static int
cmd_show(const char *in, int as_text, int annotated) {
    size_t len = 0;
    unsigned char *buf = slurp(in, &len);
    if(!buf) return 1;
    if(as_text < 0) as_text = looks_like_text(buf, len);

    ProfileElement_t *pe[MAX_PE];
    int lines[MAX_PE];
    int n = read_package(buf, len, as_text, pe, lines, MAX_PE);
    free(buf);
    if(n < 0) { report_parse_error(); return 1; }

    vn_options_t o = {0};
    o.mode = annotated ? VN_MODE_ANNOTATED : VN_MODE_PRETTY;
    o.annotations = &vn_generated_annotations;
    for(int i = 0; i < n; i++) {
        printf("value%d ProfileElement ::= ", i + 1);
        if(vn_fprint(stdout, &asn_DEF_ProfileElement, pe[i], &o) < 0) return 1;
        putchar('\n');
    }
    return 0;
}

static int
cmd_check(const char *in, int as_text, const char *rules, const char *skel,
          int strict, int as_json, int no_rules) {
    size_t len = 0;
    unsigned char *buf = slurp(in, &len);
    if(!buf) return 1;
    if(as_text < 0) as_text = looks_like_text(buf, len);

    ProfileElement_t *pe[MAX_PE];
    int lines[MAX_PE];
    int n = read_package(buf, len, as_text, pe, lines, MAX_PE);
    if(n < 0) {
        /* The reader states a line and a column. An editor can mark that
           exactly, which is the one case where it can. */
        int line = 1, column = 1;
        sscanf(g_parse_error, "line %d column %d", &line, &column);
        const char *colon = strstr(g_parse_error, ": ");
        const char *msg = colon ? colon + 2 : g_parse_error;
        if(as_json) {
            printf("{\n \"findings\": [");
            json_finding(1, "error", "parse", msg, line, column, NULL);
            printf("\n ],\n \"elements\": 0,\n \"fired\": 0\n}\n");
        } else {
            fprintf(stderr, "euicc: cannot read profile element %d: %s\n",
                    g_parse_element, g_parse_error);
        }
        free(buf);
        return 1;
    }
    free(buf);

    /*
     * Everything that can fail to run comes before the first byte of output.
     * The JSON prologue used to be printed first, so a missing rule directory
     * or skeleton left an unterminated object on stdout; an editor then said
     * "did not write JSON" and threw away the stderr line that named the real
     * cause. Exit 2 now means stdout stayed empty and stderr says why.
     *
     * --no-rules is the reader and the constraints without the rule set: what
     * an editor asks at every pause in typing, where the prose rules would be
     * recomputed against text that is mid-edit anyway. It also never opens the
     * rule engine, so a machine whose rules or transforms are missing still
     * gets its parse and constraint findings while writing.
     */
    sch_engine_t *e = NULL;
    xmlDocPtr doc = NULL;
    sch_result_t res = {0};

    if(!no_rules) {
        e = sch_open(rules, skel);
        if(!e) return 2;

        doc = package_to_xml(pe, n);
        if(!doc) {
            fprintf(stderr, "euicc: cannot render the package as XML\n");
            sch_close(e);
            return 2;
        }

        if(sch_validate(e, doc, &res) != 0) {
            xmlFreeDoc(doc);
            sch_close(e);
            return 2;
        }
    }

    int bad = 0, first = 1;
    if(as_json) printf("{\n \"findings\": [");
    for(int i = 0; i < n; i++) {
        char reason[512];
        size_t rlen = sizeof reason;
        if(vn_check_constraints(&asn_DEF_ProfileElement, pe[i], reason, &rlen) != 0) {
            if(as_json) {
                json_finding(first, "error", "schema", reason, lines[i], 1, NULL);
                first = 0;
            } else {
                printf("  schema   profile element %d: %s\n", i + 1, reason);
            }
            bad++;
        }
    }

    int errors = 0, warnings = 0;
    for(size_t i = 0; i < res.count; i++) {
        sch_finding_t *f = &res.findings[i];
        int is_warning = f->role && !strcmp(f->role, "warning");
        if(is_warning) warnings++; else errors++;
        if(as_json) {
            int idx = element_of(f->location);
            json_finding(first, is_warning ? "warning" : "error",
                         f->id ? f->id : "?", f->text ? f->text : "",
                         idx > 0 && idx <= n ? lines[idx - 1] : 1, 1,
                         f->rule_file);
            first = 0;
        } else {
            printf("  %-8s %-13s %s\n", is_warning ? "warning" : "error",
                   f->id ? f->id : "?", f->text ? f->text : "");
            if(f->location) printf("           %-13s %s\n", "at", f->location);
        }
    }

    if(as_json) {
        printf("\n ],\n \"elements\": %d,\n \"fired\": %zu\n}\n", n, res.fired);
        sch_result_free(&res);
        xmlFreeDoc(doc);
        sch_close(e);
        return (errors + bad) || (strict && warnings) ? 1 : 0;
    }

    /* The count is not decoration. A rule whose context does not occur in a
       package did not pass: it did not run. This counts rule instances, which
       is how many times a context matched, and not how many distinct rules
       exist. A package of 30 elements fires the same rule many times. */
    printf("\n%s: %d error%s, %d warning%s, %zu rule instances fired over "
           "%d profile element%s\n",
           in ? in : "stdin", errors + bad, (errors + bad) == 1 ? "" : "s",
           warnings, warnings == 1 ? "" : "s", res.fired, n, n == 1 ? "" : "s");

    sch_result_free(&res);
    xmlFreeDoc(doc);
    sch_close(e);
    return (errors + bad) || (strict && warnings) ? 1 : 0;
}

/*
 * diff compares a source file against a package. It writes nothing and judges
 * nothing: `check` states whether a package is correct, and repeating that
 * here would be a second answer to the same question.
 *
 * The comparison earns its place where git diff cannot go, with text on one
 * side and bytes on the other.
 */
static int
cmd_diff(const char *a_path, const char *b_path, int as_json) {
    if(!a_path || !b_path) {
        fprintf(stderr, "euicc: diff needs two files\n");
        return 2;
    }

    ProfileElement_t *a[MAX_PE], *b[MAX_PE];
    int a_lines[MAX_PE], b_lines[MAX_PE];
    size_t alen = 0, blen = 0;
    /*
     * The exit code is the answer, so a CI gate needs no parsing: 0 no
     * difference, 1 a difference, 2 could not compare. Failing to read a
     * file used to exit 1, indistinguishable from "the packages differ".
     */
    int rc = 2;
    xmlDocPtr ax = NULL, bx = NULL;

    unsigned char *abuf = slurp(a_path, &alen);
    if(!abuf) return 2;
    unsigned char *bbuf = slurp(b_path, &blen);
    if(!bbuf) { free(abuf); return 2; }

    int an = read_package(abuf, alen, looks_like_text(abuf, alen), a, a_lines, MAX_PE);
    if(an < 0) {
        fprintf(stderr, "euicc: cannot read %s: %s\n", a_path, g_parse_error);
        goto done;
    }
    int bn = read_package(bbuf, blen, looks_like_text(bbuf, blen), b, b_lines, MAX_PE);
    if(bn < 0) {
        fprintf(stderr, "euicc: cannot read %s: %s\n", b_path, g_parse_error);
        goto done;
    }

    ax = package_to_xml(a, an);
    bx = package_to_xml(b, bn);
    if(!ax || !bx) {
        fprintf(stderr, "euicc: cannot render a package as XML\n");
        goto done;
    }

    if(!as_json) printf("%s against %s:\n\n", a_path, b_path);
    {
        int n = diff_report((struct ProfileElement **)a, an, ax,
                            (struct ProfileElement **)b, bn, bx, as_json);
        rc = n < 0 ? 2 : (n > 0 ? 1 : 0);
    }

done:
    if(ax) xmlFreeDoc(ax);
    if(bx) xmlFreeDoc(bx);
    free(abuf);
    free(bbuf);
    return rc;
}

/*
 * fmt reads text and writes text. It never touches the codec, the schema or the
 * rule set, so it works on a file that does not parse -- which is the file most
 * in need of laying out.
 */
static int
cmd_fmt(const char *in, int in_place) {
    if(in_place && !in) {
        fprintf(stderr, "euicc: -w needs a file\n");
        return 2;
    }
    size_t len = 0;
    unsigned char *buf = slurp(in, &len);
    if(!buf) return 1;

    char *why = NULL;
    char *out = fmt_layout((const char *)buf, len, "    ", &why);
    free(buf);
    if(!out) {
        fprintf(stderr, "euicc: %s\n", why ? why : "cannot lay out this file");
        return 1;
    }

    if(in_place) {
        FILE *f = fopen(in, "wb");
        if(!f) {
            fprintf(stderr, "euicc: cannot write %s\n", in);
            free(out);
            return 1;
        }
        fputs(out, f);
        fclose(f);
    } else {
        fputs(out, stdout);
    }
    free(out);
    return 0;
}

/*
 * fmt -l: which files are not laid out. The exit code is the answer -- 0 when
 * every file already has the canonical layout, 1 when at least one does not,
 * 2 when a file could not be read at all -- so a pre-commit hook or CI needs
 * no diffing of its own, the same contract `terraform fmt -check` gives.
 * Nothing is written; the names of the offending files go to stdout.
 */
static int
cmd_fmt_check(const char *paths[], int npaths) {
    int differs = 0;

    for(int i = 0; i < (npaths ? npaths : 1); i++) {
        const char *path = npaths ? paths[i] : NULL;
        size_t len = 0;
        unsigned char *buf = slurp(path, &len);
        if(!buf) return 2;

        char *why = NULL;
        char *out = fmt_layout((const char *)buf, len, "    ", &why);
        if(!out) {
            fprintf(stderr, "euicc: %s: %s\n", path ? path : "stdin",
                    why ? why : "cannot lay out");
            free(buf);
            return 2;
        }
        if(strlen(out) != len || memcmp(out, buf, len) != 0) {
            puts(path ? path : "(stdin)");
            differs = 1;
        }
        free(out);
        free(buf);
    }
    return differs;
}

/*
 * completion: a script for the shell, to stdout. Static text on purpose --
 * generating it from the option table would be machinery for eight commands
 * and a dozen flags -- and a test holds it to usage(): every command and
 * every flag the usage names must appear in both scripts, so the two cannot
 * drift apart without a red run.
 */
static int
cmd_completion(const char *shell) {
    if(shell && !strcmp(shell, "zsh")) {
        fputs(
"#compdef euicc\n"
"_euicc() {\n"
"  local -a cmds\n"
"  cmds=(\n"
"    'build:value notation in, DER out'\n"
"    'show:DER in, value notation out'\n"
"    'check:either in, a verdict out'\n"
"    'diff:what separates a source file from a package'\n"
"    'schema:the schema as JSON, for an editor'\n"
"    'fmt:value notation laid out, one member to a line'\n"
"    'card:ask a physical eUICC, or a recording, what it is'\n"
"    'metadata:a profile in, its StoreMetadataRequest out'\n"
"    'version:what this binary is'\n"
"    'completion:a completion script for zsh or bash'\n"
"  )\n"
"  if (( CURRENT == 2 )); then\n"
"    _describe -t commands 'euicc command' cmds\n"
"    return\n"
"  fi\n"
"  case $words[2] in\n"
"    completion) _values 'shell' zsh bash ;;\n"
"    card)\n"
"      if (( CURRENT == 3 )); then\n"
"        _values 'card subcommand' info profiles install enable disable delete\n"
"      else\n"
"        _arguments -s \\\n"
"          '--reader[the reader to use]:reader' \\\n"
"          '--replay[answer from a recording instead of a reader]:file:_files' \\\n"
"          '--record[also write every exchange to a file]:file:_files' \\\n"
"          '--server[download from a real SM-DP+ over ES9+]:url:_urls' \\\n"
"          '--server-ca[a PEM bundle to trust for --server]:file:_files' \\\n"
"          '--class[card install: the Profile Class for the metadata]:class:(test provisioning operational)' \\\n"
"          '--json[one JSON object]'\n"
"      fi\n"
"      ;;\n"
"    *) _arguments -s \\\n"
"         '-o[write here instead of to stdout]:file:_files' \\\n"
"         '-t[the input is value notation]' \\\n"
"         '-b[the input is DER or BER]' \\\n"
"         '-a[show: add X.680 comments]' \\\n"
"         '-s[check: a warning fails the run too]' \\\n"
"         '-w[fmt: write the file back]' \\\n"
"         '-l[fmt: list the files whose layout differs]' \\\n"
"         '--json[check, diff: one JSON object]' \\\n"
"         '--no-rules[check: without the rule set]' \\\n"
"         '--rules[the rule set]:directory:_files -/' \\\n"
"         '--skel[the ISO Schematron transforms]:directory:_files -/' \\\n"
"         '*:file:_files' ;;\n"
"  esac\n"
"}\n"
"_euicc \"$@\"\n", stdout);
        return 0;
    }
    if(shell && !strcmp(shell, "bash")) {
        fputs(
"_euicc() {\n"
"  local cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
"  if [ \"$COMP_CWORD\" -eq 1 ]; then\n"
"    COMPREPLY=($(compgen -W \"build show check diff schema fmt card metadata version completion\" -- \"$cur\"))\n"
"    return\n"
"  fi\n"
"  if [ \"${COMP_WORDS[1]}\" = completion ]; then\n"
"    COMPREPLY=($(compgen -W \"zsh bash\" -- \"$cur\"))\n"
"    return\n"
"  fi\n"
"  if [ \"${COMP_WORDS[1]}\" = card ]; then\n"
"    if [ \"$COMP_CWORD\" -eq 2 ]; then\n"
"      COMPREPLY=($(compgen -W \"info profiles install enable disable delete\" -- \"$cur\"))\n"
"    else\n"
"      COMPREPLY=($(compgen -W \"--reader --replay --record --class --provider --name --json --server --server-ca\" -- \"$cur\"))\n"
"    fi\n"
"    return\n"
"  fi\n"
"  case \"$cur\" in\n"
"    -*) COMPREPLY=($(compgen -W \"-o -t -b -a -s -w -l --json --no-rules --rules --skel\" -- \"$cur\")) ;;\n"
"    *)  COMPREPLY=($(compgen -f -- \"$cur\")) ;;\n"
"  esac\n"
"}\n"
"complete -F _euicc euicc\n", stdout);
        return 0;
    }
    fprintf(stderr, "euicc: completion takes zsh or bash\n");
    return 2;
}

/* ---- entry --------------------------------------------------------------- */

static void
usage(void) {
    fputs(
        "usage: euicc <command> [options] [file]\n"
        "       euicc diff <source> <package>\n"
        "       euicc card info|profiles|install|enable|disable|delete [options]\n"
        "\n"
        "  build    value notation in, DER out\n"
        "  show     DER in, value notation out\n"
        "  check    either in, a verdict out\n"
        "  diff     what separates a source file from a package\n"
        "  schema   the schema as JSON, for an editor\n"
        "  fmt      value notation laid out, one member to a line\n"
        "  card     ask a physical eUICC, or a recording, what it is\n"
        "  metadata a profile in, its StoreMetadataRequest out -- what an\n"
        "           SM-DP+ needs before a card is involved\n"
        "  version  what this binary is, for a bug report or an editor\n"
        "  completion  a completion script for zsh or bash, to stdout\n"
        "\n"
        "options:\n"
        "  -o FILE     write here instead of to stdout\n"
        "  -t          the input is value notation\n"
        "  -b          the input is DER or BER\n"
        "  -a          show: add X.680 comments\n"
        "  -w          fmt: write the file back instead of to stdout\n"
        "  -l          fmt: list the files whose layout differs, and say so in\n"
        "              the exit code -- what a pre-commit hook or CI runs\n"
        "  -s          check: a warning fails the run too\n"
        "  --json      check, diff, card: one JSON object, for an editor or a\n"
        "              script\n"
        "  --no-rules  check: the reader and the constraints, without the rule set\n"

        "  --rules DIR the rule set, default " EUICC_RULES_DIR "\n"
        "  --skel DIR  the ISO Schematron transforms\n"
        "  --class C   card install: the Profile Class to put in the metadata,\n"
        "              one of test, provisioning or operational. Left out\n"
        "              entirely when not given, which an eUICC reads as\n"
        "              operational -- but a Test Profile has to say so\n"
        "              (SGP.22 section 2.4.5.3)\n"
        "  --reader NAME  card: the reader to use, default the only one attached\n"
        "  --replay FILE  card: answer from a recording instead of a reader --\n"
        "                 what lets info's happy path run with no hardware\n"
        "                 attached, and what replays a colleague's capture\n"
        "  --record FILE  card: also write every exchange to FILE, in the\n"
        "                 format --replay reads back\n"
        "  --server URL   card install: download from a real SM-DP+ over\n"
        "                 ES9+ instead of building the package here. The\n"
        "                 Profile, its metadata and every signature then\n"
        "                 come from that server, so no file is given and\n"
        "                 --provider, --name and --class do not apply\n"
        "  --server-ca FILE  card install: a PEM bundle to trust for\n"
        "                 --server, for a server whose certificate does\n"
        "                 not chain to a public root\n"
        "\n"
        "Without -t or -b the input is read as value notation when it is text.\n"
        "diff and fmt -l answer in the exit code: 0 no difference, 1 a\n"
        "difference, 2 the question could not be answered.\n"
        "\n"
        "card info's exit code is a verdict, not merely whether it ran: 0\n"
        "the card answered and trusts this project's test Certificate\n"
        "Issuer (its test credentials will work with this card), 1 the card\n"
        "answered and does not, 2 the question could not be asked at all --\n"
        "no reader, no card, no ISD-R, or an answer that made no sense.\n"
        "\n"
        "card profiles' exit code answers a different question, not a\n"
        "verdict about trust: 0 means the profile list was retrieved,\n"
        "whatever it contains -- an empty list is a complete and real\n"
        "answer, not this command failing to find anything. 1 means the\n"
        "eUICC answered and refused the request. 2 means the question\n"
        "could not be asked at all -- no reader, no card, no ISD-R, or an\n"
        "answer that made no sense.\n",
        stderr);
}

int
main(int argc, char **argv) {
    if(argc < 2) { usage(); return 2; }

    const char *cmd = argv[1];

    /* card has its own subcommand (info, profiles) and its own flags
       (--reader, --record, --replay), no overlap with the -t/-b/-o
       vocabulary the loop below parses for every other command, and no
       use for libxml2/libxslt either -- so it is dispatched before any
       of that runs, not folded into the shared loop. */
    if(!strcmp(cmd, "card")) return cmd_card(argc - 2, argv + 2);
    if(!strcmp(cmd, "metadata")) {
        const char *path = NULL, *out = NULL, *spn = NULL, *name = NULL;
        int profile_class = -1;
        for(int i = 2; i < argc; i++) {
            if(!strcmp(argv[i], "-o") && i + 1 < argc) out = argv[++i];
            else if(!strcmp(argv[i], "--provider") && i + 1 < argc) spn = argv[++i];
            else if(!strcmp(argv[i], "--name") && i + 1 < argc) name = argv[++i];
            else if(!strcmp(argv[i], "--class") && i + 1 < argc) {
                const char *c = argv[++i];
                if(!strcmp(c, "test")) profile_class = 0;
                else if(!strcmp(c, "provisioning")) profile_class = 1;
                else if(!strcmp(c, "operational")) profile_class = 2;
                else {
                    fprintf(stderr, "euicc: metadata: --class takes test, "
                                    "provisioning or operational, not %s\n", c);
                    return 2;
                }
            }
            else if(argv[i][0] != '-' && !path) path = argv[i];
            else { usage(); return 2; }
        }
        return cmd_metadata(path, out, spn, name, profile_class);
    }
    const char *in = NULL, *out = NULL;
    const char *rules = EUICC_RULES_DIR, *skel = EUICC_SKEL_DIR;
    const char *files[256];
    int nfiles = 0;
    int as_text = -1, annotated = 0, strict = 0, as_json = 0, in_place = 0;
    int no_rules = 0, list_only = 0;
    const char *second = NULL;

    for(int i = 2; i < argc; i++) {
        if(!strcmp(argv[i], "-o") && i + 1 < argc) out = argv[++i];
        else if(!strcmp(argv[i], "--rules") && i + 1 < argc) rules = argv[++i];
        else if(!strcmp(argv[i], "--skel") && i + 1 < argc) skel = argv[++i];
        else if(!strcmp(argv[i], "-t")) as_text = 1;
        else if(!strcmp(argv[i], "-b")) as_text = 0;
        else if(!strcmp(argv[i], "-a")) annotated = 1;
        else if(!strcmp(argv[i], "-w")) in_place = 1;
        else if(!strcmp(argv[i], "-l")) list_only = 1;
        else if(!strcmp(argv[i], "-s")) strict = 1;
        else if(!strcmp(argv[i], "--json")) as_json = 1;
        else if(!strcmp(argv[i], "--no-rules")) no_rules = 1;

        else if(argv[i][0] == '-' && argv[i][1]) { usage(); return 2; }
        else {
            if(nfiles < (int)(sizeof files / sizeof *files))
                files[nfiles++] = argv[i];
            if(!second) second = argv[i];
            else in = argv[i];
        }
    }

    /* Every command but diff takes one file, and it arrives first. */
    if(strcmp(cmd, "diff") != 0 && !in) { in = second; second = NULL; }

    xmlInitParser();
    int rc;
    if(!strcmp(cmd, "build")) rc = cmd_build(in, out, as_text);
    else if(!strcmp(cmd, "show")) rc = cmd_show(in, as_text, annotated);
    else if(!strcmp(cmd, "check")) rc = cmd_check(in, as_text, rules, skel, strict, as_json, no_rules);
    else if(!strcmp(cmd, "diff")) rc = cmd_diff(second, in, as_json);
    else if(!strcmp(cmd, "schema")) rc = cmd_schema(stdout);
    else if(!strcmp(cmd, "fmt")) rc = list_only
        ? cmd_fmt_check(files, nfiles)
        : cmd_fmt(in, in_place);
    else if(!strcmp(cmd, "completion")) rc = cmd_completion(in);
    else if(!strcmp(cmd, "version")) {
        printf("euicc %s (%s)\n", EUICC_VERSION, EUICC_GITSHA);
        rc = 0;
    }
    else { usage(); rc = 2; }

    xsltCleanupGlobals();
    xmlCleanupParser();
    return rc;
}
